version: '3.8'

services:
  genoblend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: genoblend_app
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/deps
      - /app/_build
    environment:
      - MIX_ENV=dev
      - PHX_HOST=localhost
    command: iex --sname genoblend --cookie genoblend -S mix phx.server
    stdin_open: true
    tty: true
